### ISSUE TITLE
ToAnotherOrDefault

### ISSUE THREAD

**Issue by kurnakovv** [kurnakovv/EnumConverter#32]
Create docs for [this](https://github.com/kurnakovv/EnumConverter/blob/main/src/EnumConverter/EnumConverter.cs#L82) method 
[Right here](https://github.com/kurnakovv/EnumConverter/blob/main/DocsReadMe.md) by analogy with another methods

**Comment by Kurnakova** [comment]
Hi.

**Comment by kurnakovv** [comment]
solved in [this](https://github.com/kurnakovv/EnumConverter/pull/65) PR
