### ISSUE TITLE
Fix TryToAnother parameters documentation

### ISSUE THREAD

**Issue by kurnakovv** [kurnakovv/EnumConverter#33]
`Enum that we want to get after convert.` -> `Enum that we want try to get after convert.` 
`Input enum we want to convert to <typeparamref name="TAnotherEnum"/>.` -> `Input enum we want try to convert to <typeparamref name="TAnotherEnum"/>.`

**Comment by Yousef-Majidi** [comment]
Hi, I'd like to try to fix this. 

Just so I understand, you want any occurrence of the text of the left of `->` to be replaced with the right side anywhere in comments. Correct?

**Comment by kurnakovv** [comment]
@Yousef-Majidi Hi! Thank you for help, I'm glad to see new contributors :)
You are right, Find all the text from the right side and replace that text from the left side.
For example:
Find text `Enum that we want to get after convert.` and replace to `Enum that we want try to get after convert.`

**Comment by Yousef-Majidi** [comment]
Will do. Could you please kindly assign this issue to me? Thank you.

**Comment by kurnakovv** [comment]
Ok, no problem :)
