### ISSUE TITLE
ToEnumOrDefault

### ISSUE THREAD

**Issue by kurnakovv** [kurnakovv/EnumConverter#61]
# ToEnumOrDefault

**Description**

Try convert string value to enum or return default value if not possible.

**Signature**

bool ToEnumOrDefault<TEnum>(this string, bool [default = true], TEnum [default = TEnum]) where TEnum : struct, Enum

**Type Parameters**

`TEnum` - Enum that we want try to get after convert.

**Parameters**

- `string stringValue` - Input string we want to convert to `TEnum`.
- `bool ignoreCase` - Ignore or regard case.
- `TEnum defaultValue` - `TEnum` or default of `TEnum`.

**Returns**
`TEnum` or `defaultValue` if not possible to convert.

**Code examples**

```csharp
public enum MyEnum { First, Second, Third }
```

```csharp
string stringValueFirst = "First";
string stringValueSecond = "Second";
string stringValueInvalid = "Blablabla";

MyEnum enumFirst = stringValueFirst.ToEnumOrDefault<MyEnum>();
MyEnum enumSecond = stringValueSecond.ToEnumOrDefault<MyEnum>(false);
MyEnum enumThird = stringValueInvalid.ToEnumOrDefault<MyEnum>(MyEnum.Third);

// output
// enumFirst - MyEnum.First
// enumSecond - MyEnum.Second
// enumThird - MyEnum.Third
```

**Comment by Kurnakova** [comment]
Hi

**Comment by Kurnakova** [comment]
@kurnakovv Hey, why do we sometimes use TAnotherEnum and sometimes TEnum, what's the difference, why do we need two?

**Comment by kurnakovv** [comment]
@Kurnakova it depends on an input parameter
`TAnotherEnum` - when you convert input **enum** to **another enum**
`TEnum` - when you convert input **string** to **enum**
In your cases you need to use `TEnum`, because input parameter is string (not enum)

I hope it's clear

**Comment by Kurnakova** [comment]
@kurnakovv 
> Returns
> "TAnotherEnum" or "defaultValue" if not possible to convert.
Why does say that it returns TAnotherEnum though? Or is this a typo?

**Comment by kurnakovv** [comment]
Good catch, fixed

**Comment by Kurnakova** [comment]
@kurnakovv
> Code Examples
> bool enumFirst = stringValueFirst.ToEnumOrDefault<MyEnum>();

Why is it bool? Shouldn't it be "MyEnum" or smth like that, since this method returns enums?
